library(tidyverse)
library(purrr)
library(sf)
install.packages("sf")
install.packages("rgeos")
install.packages("methods")
library(methods)
library(rgeos)
library(sp)
library(roxygen2)
install.packages("checkmate")
library(checkmate)
library(testthat)
ozbig <- read_sf("./data/gadm36_AUS_shp/gadm36_AUS_1.shp")
oz_st <- maptools::thinnedSpatialPoly(as(ozbig, "Spatial"), tolerance = 0.1, minarea = 0.001, topologyPreserve = TRUE)
Aus <- st_as_sf(oz_st)

devtools::use_data(Aus,overwrite=TRUE)
